apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: headlamp-ingress
  namespace: headlamp
spec:
  rules:
    - host: headlamp.arriaga.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubernetes-headlamp
                port:
                  number: 80
