apiVersion: v1
kind: Secret
metadata:
  name: vault-client-secrets
  namespace: vault
type: Opaque
stringData:
  vault-addr: "http://vault.vault.svc.cluster.local:8200"
  vault-token: "12345Abcde"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-client
  namespace: vault
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: vault-client
  template:
    metadata:
      labels:
        app: vault-client
    spec:
      containers:
        - name: vault-client
          image: hashicorp/vault:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: VAULT_ADDR
              valueFrom:
                secretKeyRef:
                  name: vault-client-secrets
                  key: vault-addr
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-client-secrets
                  key: vault-token
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
